# Generated by Django 4.2.25 on 2026-08-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_teacherinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='employee_no',
        ),
    ]
