# Generated by Django 4.2.25 on 2026-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_userexamattempt_userexamanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexamattempt',
            name='correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='skipped_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='wrong_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
