# Generated by Django 4.2.25 on 2026-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_examresultfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=150)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('correct_answers', models.IntegerField(blank=True, null=True)),
                ('wrong_answers', models.IntegerField(blank=True, null=True)),
                ('skipped_answers', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result_status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'staging_exam_results',
            },
        ),
    ]
