# Generated by Django 4.2.25 on 2026-09-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_stagingexamresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StagingExamResult',
        ),
    ]
